import { NostalgiaPlayer } from "../components/nostalgia-player";
export const songs = [
["Channa Mereya","Ae Dil Hai Mushkil"],["Agar Tum Saath Ho","Tamasha"],["O Bedardeya","Tu Jhoothi Main Makkaar"],["Tujhe Bhula Diya","Anjaana Anjaani"],["Hamari Adhuri Kahani","Hamari Adhuri Kahani"],["Jag Soona Soona Lage","Om Shanti Om"],["Sach Keh Raha Hai Deewana","Rehnaa Hai Terre Dil Mein"],["Tadap Tadap Ke","Hum Dil De Chuke Sanam"],["Tune Jo Na Kaha","New York"],["Tanhayee","Dil Chahta Hai"],["Bhula Dena","Aashiqui 2"],["Main Dhoondne Ko Zamaane Mein","Heartless"],["Kahin Toh","Jaane Tu... Ya Jaane Na"],["Beete Lamhein","The Train"],["Yeh Dooriyaan","Love Aaj Kal"],["Mera Kuch Saamaan","Ijaazat"],["Tujhse Naraz Nahi Zindagi","Masoom"],["Tere Bina Zindagi Se","Aandhi"],["Kahi Door Jab Din Dhal Jaye","Anand"],["Chitthi Aayi Hai","Naam"]
] as const;
export default function Home() { return <main className="relative flex min-h-dvh flex-1 flex-col items-center justify-between overflow-hidden bg-[#090a0e]">
<div aria-hidden="true" className="hero-bg -z-20"/><div aria-hidden="true" className="fixed inset-0 -z-10 bg-gradient-to-b from-black/35 via-black/15 to-black/55"/><div aria-hidden="true" className="grain -z-10"/>
<header className="fixed left-[max(1rem,env(safe-area-inset-left))] right-[max(1rem,env(safe-area-inset-right))] top-[max(1rem,env(safe-area-inset-top))] z-10 flex items-start justify-between text-[11px] tracking-[.18em] text-white/65 uppercase sm:text-xs">
<div className="min-w-24"><p className="font-medium text-white/85">11:47 PM</p><p className="mt-1 hidden text-[9px] tracking-[.22em] text-white/40 sm:block">somewhere quiet</p></div>
<div className="absolute left-1/2 -translate-x-1/2 whitespace-nowrap text-center"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-black/15 px-3 py-1.5 backdrop-blur-md"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[var(--accent)] shadow-[0_0_10px_var(--accent)]"/>2,184 listening</span></div>
<nav aria-label="Social links" className="flex items-center gap-3 sm:gap-5"><a className="transition-colors hover:text-white" href="https://instagram.com" target="_blank" rel="noreferrer">Instagram</a><a className="hidden transition-colors hover:text-white sm:inline" href="https://x.com" target="_blank" rel="noreferrer">X</a><a className="transition-colors hover:text-white" href="#about">About</a></nav></header>
<section className="pointer-events-none fixed bottom-[calc(max(1rem,env(safe-area-inset-bottom))+7.2rem)] left-1/2 z-0 w-full max-w-3xl -translate-x-1/2 px-6 text-center sm:bottom-36"><p className="mx-auto max-w-lg text-balance text-sm leading-6 text-white/45 sm:text-base">For the nights when an old song says what you couldn’t.</p></section>
<NostalgiaPlayer songs={songs}/><footer id="about" className="fixed bottom-[max(.75rem,env(safe-area-inset-bottom))] left-1/2 z-10 hidden -translate-x-1/2 text-[10px] tracking-[.2em] text-white/30 uppercase sm:block">some nights • nostalgia radio</footer>
</main>; }