"use client";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
type Song=readonly [title:string,film:string]; type Props={songs:readonly Song[]};
const icons={prev:<path d="M6 5v14M19 6l-9 6 9 6V6Z"/>,next:<path d="M18 5v14M5 6l9 6-9 6V6Z"/>,play:<path d="m8 5 11 7-11 7V5Z" fill="currentColor" stroke="none"/>,pause:<path d="M8 5v14M16 5v14"/>};
function Icon({name,size=18}:{name:keyof typeof icons,size?:number}){return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{icons[name]}</svg>}
function formatTime(value:number){if(!Number.isFinite(value)||value<0)return "0:00";const mins=Math.floor(value/60);const secs=Math.floor(value%60).toString().padStart(2,"0");return mins+":"+secs}
const audioPath=(title:string)=>"/audio/"+title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+".mp3";
export function NostalgiaPlayer({songs}:Props){
const audioRef=useRef<HTMLAudioElement|null>(null);const [index,setIndex]=useState(0);const [playing,setPlaying]=useState(false);const [progress,setProgress]=useState(0);const [duration,setDuration]=useState(0);const [error,setError]=useState(false);const song=songs[index];
const loadSong=useCallback((nextIndex:number,autoplay=false)=>{const audio=audioRef.current;if(!audio)return;setIndex(nextIndex);setProgress(0);setDuration(0);setError(false);audio.src=audioPath(songs[nextIndex][0]);audio.load();if(autoplay)audio.play().then(()=>setPlaying(true)).catch(()=>{setPlaying(false);setError(true)})},[songs]);
useEffect(()=>{const audio=audioRef.current;if(!audio)return;const onTime=()=>setProgress(audio.currentTime);const onMeta=()=>setDuration(audio.duration);const onEnded=()=>loadSong((index+1)%songs.length,true);const onError=()=>setError(true);audio.addEventListener("timeupdate",onTime);audio.addEventListener("loadedmetadata",onMeta);audio.addEventListener("ended",onEnded);audio.addEventListener("error",onError);return()=>{audio.removeEventListener("timeupdate",onTime);audio.removeEventListener("loadedmetadata",onMeta);audio.removeEventListener("ended",onEnded);audio.removeEventListener("error",onError)}},[index,loadSong,songs.length]);
const toggle=async()=>{const audio=audioRef.current;if(!audio)return;if(playing){audio.pause();setPlaying(false);return}try{await audio.play();setPlaying(true);setError(false)}catch{setError(true);setPlaying(false)}};
const seek=(value:number)=>{const audio=audioRef.current;if(!audio)return;audio.currentTime=value;setProgress(value)};const percent=duration?Math.min(100,progress/duration*100):0;const coverStyle=useMemo(()=>({backgroundImage:"url('/bg/scene-wide.jpg')"}),[]);
const transport=(mobile=false)=><><button onClick={()=>loadSong((index-1+songs.length)%songs.length,playing)} aria-label="Previous song" className="grid h-10 w-10 place-items-center rounded-full text-white/65 transition hover:bg-white/10 hover:text-white"><Icon name="prev"/></button><button onClick={toggle} aria-label={playing?"Pause":"Play"} className={mobile?"grid h-11 w-11 place-items-center rounded-full bg-white text-black shadow-[0_8px_24px_rgba(0,0,0,.3)] transition hover:scale-105":"grid h-12 w-12 place-items-center rounded-full bg-white text-black shadow-[0_8px_25px_rgba(0,0,0,.32)] transition hover:scale-105"}><Icon name={playing?"pause":"play"} size={mobile?19:20}/></button><button onClick={()=>loadSong((index+1)%songs.length,playing)} aria-label="Next song" className="grid h-10 w-10 place-items-center rounded-full text-white/65 transition hover:bg-white/10 hover:text-white"><Icon name="next"/></button></>;
return <><audio ref={audioRef} preload="metadata"/>
<div className="fixed bottom-[max(1rem,env(safe-area-inset-bottom))] left-1/2 z-20 w-[min(92vw,36rem)] -translate-x-1/2 sm:hidden"><div className="glass rounded-[28px] p-4"><div className="flex items-center gap-3"><div className={"relative h-14 w-14 shrink-0 overflow-hidden rounded-full border border-white/15 bg-cover bg-center shadow-xl "+(playing?"vinyl-spin":"")} style={coverStyle}><div className="absolute inset-[22px] rounded-full bg-black/70 ring-2 ring-white/40"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">{song[0]}</p><p className="mt-0.5 truncate text-xs text-white/55">{song[1]}</p></div>{transport(true)}</div><div className="seek-wrap relative mt-3 h-6"><div className="absolute left-0 right-0 top-1/2 h-[3px] -translate-y-1/2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[var(--accent)] shadow-[0_0_10px_rgba(233,173,109,.75)]" style={{width:percent+"%"}}/></div><input className="seek-range" type="range" min={0} max={duration||0} step="0.1" value={Math.min(progress,duration||0)} onChange={e=>seek(Number(e.target.value))} aria-label="Seek"/></div><div className="mt-0.5 flex justify-between text-[10.5px] tabular-nums text-white/40"><span>{formatTime(progress)}</span><span>{formatTime(duration)}</span></div>{error&&<p className="mt-2 text-center text-[10px] text-white/40">Add the matching MP3 to <code>public/audio</code> to hear this track.</p>}</div></div>
<div className="fixed bottom-[max(1.25rem,env(safe-area-inset-bottom))] left-1/2 z-20 hidden w-[min(92vw,46rem)] -translate-x-1/2 sm:flex"><div className="glass flex w-full items-center gap-4 rounded-full p-3 pr-5"><div className={"relative h-20 w-20 shrink-0 overflow-hidden rounded-full border border-white/15 bg-cover bg-center shadow-2xl "+(playing?"vinyl-spin":"")} style={coverStyle}><div className="absolute left-1/2 top-1/2 h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-black/70 ring-2 ring-white/40"/></div><div className="min-w-0 flex-1 self-stretch py-1"><div className="flex h-6 min-w-0 items-center gap-2 pr-2"><div className="min-w-0 flex-1 truncate text-[15px] font-semibold">{song[0]}</div><div className="hidden shrink-0 text-[10.5px] tabular-nums text-white/35 xs:block">{formatTime(progress)} / {formatTime(duration)}</div></div><div className="truncate text-[12.5px] text-white/70">{song[1]}</div><div className="seek-wrap relative mt-1 h-6"><div className="absolute left-0 right-0 top-1/2 h-[3px] -translate-y-1/2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[var(--accent)] shadow-[0_0_12px_rgba(233,173,109,.8)]" style={{width:percent+"%"}}/></div><input className="seek-range" type="range" min={0} max={duration||0} step="0.1" value={Math.min(progress,duration||0)} onChange={e=>seek(Number(e.target.value))} aria-label="Seek"/></div><div className="flex justify-between text-[10.5px] tabular-nums text-white/40"><span>{formatTime(progress)}</span><span>{formatTime(duration)}</span></div></div><div className="flex shrink-0 items-center gap-1">{transport()}</div></div></div></>}